### ISSUE TITLE
add chat page 

### ISSUE THREAD

**Issue by alirayaneh** [yangjiakai/lux-admin-vuetify3#1]
hi can you add chat app to this themplate ?

**Comment by yangjiakai** [comment]
Hello, thank you for your interest in my project.

I am currently developing a chat app and you are welcome to check it out on GitHub at https://github.com/yangjiakai/vuetify3-openai.

You can also view the live demo of the project at https://openai.vuetify3.com/.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangjiakai/jk-vuetify3-lux-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月19日(星期天) 晚上9:46
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[yangjiakai/jk-vuetify3-lux-admin] add chat page  (Issue #1)





 
hi can you add chat app to this themplate ?

**Comment by alirayaneh** [comment]
thanx its good . 
can you add all component that are in this demo 
https://lux-admin-pro.indielayer.com/apps/chat/channel/general

**Comment by yangjiakai** [comment]
Sorry, Vuetify official has not provided the template code for lux-admin-pro vuetify3 version. I will keep updating this project and try to complete and submit all the components used in lux-admin-pro as soon as possible, which will take some time.

**Comment by alirayaneh** [comment]
Yes, thank you. I downloaded this template from your repositories. It was very useful for me, but I needed the chat section and I couldn't find anything. On the other hand, the paid version is very expensive and I couldn't buy it. I would appreciate it if you could provide me with a complete version of Lux Admin Pro. My email address is [php.modern@gmail.com](mailto:php.modern@gmail.com).
