### ISSUE TITLE
发送消息过后等待的过程，可以让输入框有个加载等待的提示，就像chatgpt官方的那样

### ISSUE THREAD

**Issue by godotg** [yangjiakai/lux-admin-vuetify3#12]
![image](https://user-images.githubusercontent.com/34591889/235086705-2153b33a-282b-48fc-9f83-09667b8f1332.png)

发送消息过后等待的过程，可以让输入框有个加载等待的提示，就像chatgpt官方的那样。

这个等待的机器人也可以动作适当大一点，或者换一张图片，要不然没啥区分度

**Comment by godotg** [comment]
输入反馈有点低，用游戏的术语来说打击感不强

**Comment by godotg** [comment]
这个流式处理比较消耗带宽，大部分应该都是用chatbot1去做，那么这个时候就应该让等待的时候反馈强烈一点

**Comment by yangjiakai** [comment]
chatbot1已增加反馈
