### ISSUE TITLE
可以docker-compose部署吗，npm部署出现如下问题

### ISSUE THREAD

**Issue by knigth95** [yangjiakai/lux-admin-vuetify3#13]
系统：ubuntu22
权限：root
执行 npm run dev后
error：
file:///home/knight-oracle/zzm_bot/lux-admin-vuetify3/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

**Comment by godotg** [comment]
弄得js是什么版本
@knigth95

**Comment by godotg** [comment]
@knigth95 你的nodejs是什么版本？

**Comment by knigth95** [comment]
> @knigth95你的nodejs是什么版本？

v12.22.9

**Comment by godotg** [comment]
node版本过低，升级到最新的node

**Comment by godotg** [comment]
> > @knigth95你的nodejs是什么版本？
> 
> v12.22.9

升级node版本

**Comment by hasakey** [comment]
升级了也没用
