### ISSUE TITLE
chatbot1提问完问题过后应该重新把位置定位到最下面

### ISSUE THREAD

**Issue by godotg** [yangjiakai/lux-admin-vuetify3#14]
chatbot1提问完问题过后应该重新把位置定位到最下面，把scroll滚轮滚到最下方

**Comment by godotg** [comment]
不然无法感知到是否生成了回答

**Comment by yangjiakai** [comment]
上次更改整个layout的引发的bug，重新给Message区域设置了固定高度，相对的，手机端Appbar也使用了固定高度
