### ISSUE TITLE
优化手机端操作体验，手机端侧边栏前三次应该自动打开

### ISSUE THREAD

**Issue by godotg** [yangjiakai/lux-admin-vuetify3#15]
首次使用网站的时候，侧边栏前三次应该自动打开，这样可以给用户一个引导。

要不然很多用户感知不到还有侧边栏

**Comment by godotg** [comment]
就像pc网页版也会自动打开一样，变相给一个简单的提示

**Comment by yangjiakai** [comment]
侧边栏显示变量持久化了，第一次打开是默认显示，以后只要用户关掉打开就是默认关闭
