### ISSUE TITLE
网页一直显示：正在加载

### ISSUE THREAD

**Issue by xding2** [yangjiakai/lux-admin-vuetify3#31]
我按照指令：
git clone https://github.com/yangjiakai/lux-admin-vuetify3.git

cd lux-admin-vuetify3

npm install

npm run dev

运行之后，尝试在localhost：4399中查看运行的结果，但是网页一直显示，正在加载。请问有类似的问题有人遇到过嘛？诚心求教如何解决，感谢！！

我的环境如下：
node -v
v20.2.0

npm -v
9.7.2

**Comment by yangjiakai** [comment]
使用Vite初次编译时间有点久，大约需要等待一两分钟，只要没有报错，等等就好了

**Comment by xding2** [comment]
谢谢您的回答，问题已经解决了。初次编译果然是时间有点久，再次感谢您的分享！
